title: diagnosticls-configs-nvim
url: 'https://github.com/creativenull/diagnosticls-configs-nvim'
description: An unofficial collection of linters and formatters configured for diagnostic-languageserver for neovim.
